(define (problem strips-gripper-x-2)
   (:domain gripper-strips)
   (:objects rooma roomb ball1 ball2 left right)
   (:init (room rooma)
          (room roomb)
          (ball ball1)
          (ball ball2)
          (gripper left)
          (gripper right)
          (at-robby rooma)
          (at ball1 rooma)
          (at ball2 rooma)
          (free left)
          (free right))
   (:goal (and
               (at ball1 roomb)
               (at ball2 roomb))))
